INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_1", "category_1", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_2", "category_2", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_3", "category_3", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_4", "category_4", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_5", "category_5", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_6", "category_6", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_7", "category_7", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_8", "category_8", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_9", "category_9", 100, 010101, 010201);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_10", "category_10", 100, 010101, 010201);

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 15, 6);

INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim_2", 25);
INSERT INTO users (name, age) VALUES ("Jim_3", 25);
INSERT INTO users (name, age) VALUES ("Jim_4", 25);
INSERT INTO users (name, age) VALUES ("Jim_5", 25);
INSERT INTO users (name, age) VALUES ("Jim_6", 25);
INSERT INTO users (name, age) VALUES ("Jim_9", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);
INSERT INTO users (name, age) VALUES ("Jim", 25);